// three-stage/w3_VueX/my_project/src/pages/Home.vue
<template>
  <div>
    <el-carousel trigger="click" height="150px">
      <el-carousel-item v-for="item in 7" :key="item">
        <h3 class="small">{{ item }}</h3>
        <!-- <img :src="item" alt=""> -->
      </el-carousel-item>
    </el-carousel>  

    <el-row :gutter="20">
      <el-col :span="6" v-for="item in recommed" :key="item.id" @click.native="goto(item.id)">
        <img :src="item.imgurl" alt="" style="width: 100px; height: 100px">
        <h4>{{item.name}}</h4>
        <p class="price"><del>￥：{{(item.price*1).toFixed(2)}}</del><span>￥：{{(item.price*0.8).toFixed(2)}}</span></p>
      </el-col>
    </el-row>
  </div>
</template>

<script>

// 引入插件
import Vue from 'vue'
import {Carousel,CarouselItem} from 'element-ui'
Vue.use(Carousel);
Vue.use(CarouselItem)


export default {
    data() {
        return {
            recommed:[]
        }
    },
    methods: {
      // 点击跳转到详情页，并把商品id传过去
      goto(id){
        this.$router.push({name:'Goods',params:{id}})
      }
    },
    computed: {
      
    },
    async created(){
      let {data} = await this.$axios.get('/goods')
      // console.log(data);
      this.recommed = data.data.slice(0,20);
      // console.log(this.recommed);
      
    }
};
</script>

<style scoped>
    h3{
        text-align: center;
        font-size: 30px;
        color: red
    }
    h4{
      font-size: 14px;
      color: blue
    }
    .price{
      font-size:12px; 
    }
    del{
        color:#999;
    }
    span{
      margin-left:5px;color:#f00;
    }

</style>

// three-stage/w6_React-project/my-project/src/pages/Home/index.js
import React from 'react'
import {api} from '../../utile'
import {Carousel,Row,Col} from 'antd'


class Home extends React.Component{
    constructor(){
        super();
        this.state = {
            advlist:[],
            goodslist:[]
        }
        this.goto = this.goto.bind(this)
    }
    async componentWillMount(){
        let {data} = await api.get('index.php?act=index',{

        })
        // console.log(data)
        let advlist = data.datas[0].adv_list.item
        let goodslist = data.datas.slice(1).map(item=>item.goods)
        this.setState({
            advlist,
            goodslist
        })
    }
    goto(id){
        // console.log(id);
        let {history} = this.props
        history.push({
            pathname:'/goods/'+id
        })
        
    }
    render(){
        let {advlist,goodslist} = this.state
        return <div>
            {/* 轮播图 */}
            <Carousel>
                {
                    advlist.map(item=><div key={item.data}>
                            <img src={item.image} alt={item.data} style={{width:'100%'}} />                        
                        </div>)
                } 
            </Carousel>
            {/* 商品列表 */}
            {
                goodslist.map(({title,item})=>{
                    return <div key={title} style={{padding:'0 10px'}}>
                        <h2>{title}</h2>
                        <Row gutter={16}>
                            {
                                item.map(data=><Col onClick={this.goto.bind(this,data.goods_id)} key={data.goods_id} className="gutter-row" span={12} style={{height:'300px'}}>
                                    <img src={data.goods_image} alt={data.goods_name} style={{width:'90%'}}/>
                                    <h4>{data.goods_name}</h4>
                                    <p className="price"><del>{data.goods_price}</del><span style={{marginLeft:'10px',color:'red'}}>{data.goods_promotion_price}</span></p>
                                    </Col>)
                            }                           
                        </Row>
                    </div>
                })
            }
                
        </div>
    }
}

export default Home
